import React, { useState } from "react";
import { draftDocument, downloadPitchbook } from "../lib/api";
import { DEMO_REPORT_HISTORY, getActiveDealMeta, getActiveReport } from "../lib/dealUtils";

export default function ReportsPage() {
  const meta = getActiveDealMeta();
  const report = getActiveReport();
  const [output, setOutput] = useState("");
  const [history, setHistory] = useState(DEMO_REPORT_HISTORY);
  const [error, setError] = useState("");

  const recordHistory = (name) => {
    setHistory([{ name, generatedBy: "Deal Team", date: new Date().toISOString().slice(0, 10), status: "Draft" }, ...history]);
  };

  const generateDraft = async (documentType) => {
    setError("");
    try {
      const data = await draftDocument({
        document_type: documentType,
        deal_name: meta.dealName,
        buyer_name: meta.buyerName,
        seller_name: meta.targetName,
        jurisdiction: "Delaware",
        purchase_price: Number(meta.dealValue || report?.valuation?.enterprise_value || 0),
        exclusivity_days: 45,
      });
      setOutput(data.draft?.body || "Draft generated.");
      recordHistory(documentType === "LOI" ? "Letter of Intent" : "Non-Disclosure Agreement");
    } catch (e) {
      setError(e?.response?.data?.detail || "Draft generation failed.");
    }
  };

  const generatePitchbook = async () => {
    setError("");
    try {
      const blob = await downloadPitchbook({ ...report, deal_id: report.deal_id || "active-deal" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${meta.transactionCode}_pitchbook.pptx`;
      a.click();
      URL.revokeObjectURL(url);
      recordHistory("Pitchbook");
    } catch (e) {
      setError(e?.response?.data?.detail || "Pitchbook generation failed.");
    }
  };

  const downloadText = (name, content) => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = name;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="page">
      <section className="page-header">
        <div><p className="eyebrow">Output Center</p><h2>Reports</h2></div>
      </section>

      <section className="action-grid reports-actions">
        <button onClick={() => generateDraft("LOI")}>Generate LOI</button>
        <button onClick={() => generateDraft("NDA")}>Generate NDA</button>
        <button onClick={() => { setOutput("Board memo prepared for investment committee review."); recordHistory("Board Memo"); }}>Generate Board Memo</button>
        <button onClick={() => { setOutput(JSON.stringify(report.legal_risks || {}, null, 2)); recordHistory("Risk Summary"); }}>Generate Risk Summary</button>
        <button onClick={generatePitchbook}>Generate Pitchbook</button>
        <button className="secondary-button" onClick={() => downloadText(`${meta.transactionCode}_deal_report.txt`, JSON.stringify(report, null, 2))}>Download Full Deal Report</button>
      </section>

      <section className="table-panel">
        <div className="section-title"><p className="eyebrow">Generated Reports</p><h3>History</h3></div>
        <table className="data-table">
          <thead><tr><th>Report</th><th>Generated By</th><th>Date</th><th>Status</th></tr></thead>
          <tbody>{history.map((item, index) => <tr key={`${item.name}-${index}`}><td>{item.name}</td><td>{item.generatedBy}</td><td>{item.date}</td><td>{item.status}</td></tr>)}</tbody>
        </table>
      </section>

      {output && <section className="panel-flat"><div className="section-title"><p className="eyebrow">Preview</p><h3>Generated Output</h3></div><pre className="document-preview">{output}</pre></section>}
      {error && <p className="error-text">{error}</p>}
    </div>
  );
}

